apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: openwhisk-java-app
  namespace: default
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/bluebosh/openwhisk-java-app:latest
