apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: java-runtime-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/apache/openwhisk-devtools.git
    - name: revision
      value: refs/pull/297/head
