apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: javascript-runtime-git
spec:
  type: git
  params:
    - name: url
      value: https://github.com/apache/openwhisk-runtime-nodejs.git
