apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-app-image
spec:
  serviceAccountName: openwhisk-app-builder
  pipelineRef:
    name: build-openwhisk-app
  params:
    - name: OW_APP_PATH
      value: "app-git/packages/left-pad/"
    - name: OW_ACTION_NAME
      value: "openwhisk-padding-app"
  resources:
    - name: java-runtime-git
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/apache/openwhisk-devtools.git
          - name: revision
            value: refs/pull/297/head
    - name: javascript-runtime-git
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/apache/openwhisk-runtime-nodejs.git
    - name: app-git
      resourceSpec:
        type: git
        params:
          - name: url
            value: https://github.com/apache/openwhisk-test.git
    - name: app-image
      resourceSpec:
        type: image
        params:
          - name: url
            value: docker.io/bluebosh/openwhisk-padding-app
